# Generated by Django 2.1.7 on 2019-12-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('key', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('treatment_gender', models.TextField()),
                ('treatment_pronoun', models.TextField()),
                ('treatment_1', models.TextField()),
                ('treatment_2', models.TextField()),
                ('treatment_3', models.TextField()),
                ('treatment_complete', models.DateTimeField()),
                ('mediator_story', models.TextField()),
                ('mediator_complete', models.DateTimeField()),
                ('leaders_1', models.TextField()),
                ('leaders_2', models.TextField()),
                ('leaders_3', models.TextField()),
                ('leaders_4', models.TextField()),
                ('leaders_5', models.TextField()),
                ('leaders_6', models.TextField()),
                ('leaders_complete', models.DateTimeField()),
                ('proposals_1', models.TextField()),
                ('proposals_2', models.TextField()),
                ('proposals_3', models.TextField()),
                ('proposals_4', models.TextField()),
                ('proposals_5', models.TextField()),
                ('proposals_6', models.TextField()),
                ('proposals_7', models.TextField()),
                ('proposals_8', models.TextField()),
                ('proposals_complete', models.DateTimeField()),
                ('lgbt_1', models.TextField()),
                ('lgbt_2', models.TextField()),
                ('lgbt_complete', models.DateTimeField()),
                ('lgbt_social_1', models.TextField()),
                ('lgbt_social_2', models.TextField()),
                ('lgbt_social_complete', models.DateTimeField()),
                ('qualifier_1', models.TextField()),
                ('qualifier_2', models.TextField()),
                ('qualifier_3', models.TextField()),
                ('qualifier_complete', models.DateTimeField()),
                ('demographics_1', models.TextField()),
                ('demographics_2', models.TextField()),
                ('demographics_3', models.TextField()),
                ('demographics_4', models.TextField()),
                ('demographics_complete', models.DateTimeField()),
            ],
        ),
    ]
