# Generated by Django 2.1.7 on 2019-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
