# Generated by Django 2.1.7 on 2020-01-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_auto_20191211_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='qualifier_1',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='qualifier_2',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='qualifier_3',
        ),
        migrations.AddField(
            model_name='participant',
            name='country_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_from_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_from_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_from_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_from_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_from_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_to_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_to_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_to_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_to_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country_to_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='father_from',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_proficiency_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_proficiency_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_proficiency_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_proficiency_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='language_proficiency_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='mother_from',
            field=models.TextField(default=''),
        ),
    ]
