# Generated by Django 2.1.7 on 2020-01-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0006_auto_20200114_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='father_from',
            new_name='father_country',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='mother_from',
            new_name='mother_country',
        ),
    ]
