# Generated by Django 2.1.7 on 2020-01-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0007_auto_20200114_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='demographics_1',
            new_name='demographics_education',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='demographics_2',
            new_name='demographics_gender',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='demographics_3',
            new_name='demographics_politics',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='demographics_4',
            new_name='demographics_year',
        ),
    ]
