# Generated by Django 2.1.7 on 2020-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0008_auto_20200114_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='demographics_state',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='demographics_zip',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='demographics_education',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='demographics_gender',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='demographics_politics',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='demographics_year',
            field=models.TextField(default=''),
        ),
    ]
