# Generated by Django 2.1.7 on 2020-01-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0009_auto_20200114_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='feedback_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='feedback_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='recall_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='recall_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='recall_3',
            field=models.TextField(default=''),
        ),
    ]
