# Generated by Django 2.1.7 on 2020-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0010_auto_20200114_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='consent_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='feedback_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='instructions_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='welcome_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
